### ISSUE TITLE
Change default merge target to develop

### ISSUE THREAD

**Issue by DoomDuck** [Ballasi/osb#12]

**Comment by Ballasi** [comment]
Apparently GitHub defaults the merge target to the default branch of the whole project, do you think we should make develop the default branch? I'll check to see if I can block any merge request directly to `master` and check if that corrects the issue.

**Comment by DoomDuck** [comment]
Some people say that there is no good reason to have a develop branch and that tags should be used to define stable branches.
Instead of striving to have master stable

**Comment by Ballasi** [comment]
Good point but I'm unsure about users being redirected to an in-dev version of the program when they load the repository for the first time. I'll think of it

**Comment by Ballasi** [comment]
So what do you think about deleting the current master branch and renaming develop to master? I am fine with that.
